import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>MoonCoder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          MoonCoder 🌑
        </h1>

        <p className={styles.description}>
          Estude algoritmos num website{' '}
          <code className={styles.code}>100% brasileiro</code>
        </p>

        <div>
          <Link href="/start" ><button className={styles.startButton}>Começar</button></Link>
        </div>

        <div className={styles.grid}>
          <a href="https://github.com/IgorDuca" className={styles.card}>
            <h2>Github do criador &rarr;</h2>
            <p>Venha saber em quais outros projetos eu estou trabalhando</p>
          </a>

          <a href="https://rockcontent.com/br/blog/algoritmo/" className={styles.card}>
            <h2>Aprenda &rarr;</h2>
            <p>Matéria do RockContent explicando o que é um algoritmo e qual sua finalidade.</p>
          </a>
        </div>
      </main>
    </div>
  )
}

export default Home
