import type { NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import styles from '../styles/Home.module.css'
import start_styles from '../styles/Start.module.css'

const Start: NextPage = () => {
    
    const [ difficulty, setDif ] = useState("default")
    const [ buttonStatuses, setStatus ] = useState(true)
    
    return (
        <div className={styles.container}>
        <Head>
            <title>MoonCoder</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <h1 className={styles.title}>
             Configurações
            </h1>

            <div>
                <select 
                    className={start_styles.difficultySelector} 
                    onChange={(key) => { setDif(key.target.value); setStatus(false) }}
                    id="diffInput"
                >
                    <option value="default">Dificuldade</option>
                    <option value="easy">Fácil</option>
                    <option value="medium">Médio</option>
                    <option value="hard">Difícil</option>
                </select>
            </div>

            <div>
                <Link href={`/${difficulty}`}>
                    <button className={start_styles.startButton} disabled={buttonStatuses}>Começar</button>
                </Link>
            </div>
        </main>
        </div>
    )
}

export default Start
